#!/usr/bin/env ruby

require "pathname"

# Is this necessary?
# ENV["BUNDLE_GEMFILE"] ||= File.expand_path("../../Gemfile", Pathname.new(__FILE__).realpath)
# require "bundler/setup"

require "optparse"
require "string-cases"
require_relative "../lib/process_bot"

options = ProcessBot::Options.new
argv_i = 0

while argv_i < ARGV.length
  arg = ARGV.fetch(argv_i)

  if (match = arg.match(/\A--(.+)\Z/))
    key = match[1].tr("-", "_").to_sym

    if key == :path
      puts "Path: #{File.realpath("#{__dir__}/..")}"
      exit
    end

    argv_i += 1
    value = ARGV.fetch(argv_i)

    options.set(key, value)
  else
    raise "Unknown option: #{arg}"
  end

  argv_i += 1
end

ProcessBot::Process
  .new(options)
  .execute!
